apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
  labels:
    app.kubernetes.io/name: demo-hello-go
    app.kubernetes.io/instance: hello-go
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-hello-go
      app.kubernetes.io/instance: hello-go
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-hello-go
        app.kubernetes.io/instance: hello-go
    spec:
      containers:
        - name: hello-go
          image: hello-go:v0.0.0
          imagePullPolicy: IfNotPresent
          command:
            - /workspace/helloGo
          ports:
            - protocol: TCP
              containerPort: 10081
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
      imagePullSecrets:
        - name: default-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: hello-go-service
spec:
  selector:
    app.kubernetes.io/name: demo-hello-go
    app.kubernetes.io/instance: hello-go
  ports:
    - protocol: TCP
      port: 10081
      targetPort: 10081
  type: ClusterIP
